name: crypto-backtest
channels:
- conda-forge
- defaults
dependencies:
- ipython-sql=0.3.6
- nbconvert=5.3.1
- psycopg2
- pip:
  - TA-Lib==0.4.15
  - tornado==4.5.3
  - jupyter_contrib_nbextensions==0.3.3